name: CustomSlabs
version: 0.9
description: implement CustomSlabs
author: Hinchy
website: http://hinchy.us
dev-url: http://dev.bukkit.org/server-mods/customslabs/
depend: [Spout]

main:  me.bootscreen.customslabs.CustomSlabs