name: CustomSlabs
version: 0.8
description: implement CustomSlabs
author: Bootscreen
website: http://bootscreen.net
dev-url: http://dev.bukkit.org/server-mods/customslabs/
depend: [Spout]

main:  me.bootscreen.customslabs.CustomSlabs